spring:
  profiles:
    active:
    - db
  application:
    name: 321-backend
  datasource:
    url: jdbc:mysql://localhost:3310/seladb?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  spring:
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true
        sevlet:
          multipart:
            max-file-size: 10MB
  logging:
    level:
      org.hibernate.SQL: debug

supabase:
  storage:
    endpoint: https://fxydjihsycfrvhqugule.storage.supabase.co/storage/v1/s3
    endpoint_output: https://fxydjihsycfrvhqugule.storage.supabase.co/storage/v1/object/public
    bucket: test
    region: ap-southeast-1
    accessKey: 440c90412364bbc9451f9e0b722d5dc9
    secretKey: 6768fcfa0ac72d52c5b9159ad4fcb21ba42209f86c325da4011a12647d9e0e05