spring:
  profiles:
    active:
    - db
  application:
    name: 321-backend
  datasource:
    url: jdbc:mysql://localhost:3310/seladb?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  spring:
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  logging:
    level:
      org.hibernate.SQL: debug

